set_location_assignment PIN_P25 -to a[2]
set_location_assignment PIN_N26 -to a[1]
set_location_assignment PIN_n25 -to a[0]
set_location_assignment PIN_AC13 -to b[2]
set_location_assignment PIN_C13 -to b[1]
set_location_assignment PIN_B13 -to b[0]
set_location_assignment PIN_V2 -to cin
set_location_assignment PIN_AB21 -to sum[2]
set_location_assignment PIN_AC22 -to cout
set_location_assignment PIN_AF23 -to sum[1]
set_location_assignment PIN_AE23 -to sum[0]